TrabajadoresPrueba/Controllers/DepartamentosController.cs
using Microsoft.AspNetCore.Mvc;
using TrabajadoresPrueba.Data;
using TrabajadoresPrueba.Modelos;

namespace TrabajadoresPrueba.Controllers
{
    public class DepartamentosController : Controller
    {
        private readonly DataContext _context;

        public DepartamentosController(DataContext dataContext)
        {
            _context = dataContext;
        }
        public IActionResult Index()
        {
            var departamentos = _context.Departamento.ToList();
            return View(departamentos);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        public async Task<IActionResult> Create(Departamento model)
        {
            await _context.AddAsync(model); //(Insert into Departamento values 'Prueba 123'
            await _context.SaveChangesAsync(); //Commit a la base de datos 
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Edit(int id)
        {
            var departamento = await _context.Departamento.FindAsync(id);
            return View(departamento);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Departamento model)
        {
            var modelOld = await _context.Departamento.FindAsync(model.Id);
            modelOld.NombreDepartamento = model.NombreDepartamento;
            _context.Update(modelOld);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        
        public async Task<IActionResult> Delete(int id)
        {
            var departamento = await _context.Departamento.FindAsync(id);
            _context.Remove(departamento);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

TrabajadoresPrueba/Controllers/DistritosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TrabajadoresPrueba.Data;
using TrabajadoresPrueba.Modelos;

namespace TrabajadoresPrueba.Controllers
{
    public class DistritosController : Controller
    {
        private readonly DataContext _context;

        public DistritosController(DataContext dataContext)
        {
            _context = dataContext;
        }

        //GET
        public async Task<IActionResult> Index(int id) //
        {
            var distrito = await _context.Distrito.Where(x => x.IdProvincia.Equals(id)).ToListAsync();
            var modelProvincia = await _context.Provincia.FindAsync(id);
            ViewBag.Provincia = modelProvincia;
            var modelDepartamento = await _context.Departamento.FindAsync(modelProvincia.IdDepartamento);
            ViewBag.Departamento = modelDepartamento;
            return View(distrito);
        }
        //GET
        public IActionResult Create(int idProvincia) //trae el id Provincia
        {

            var distrito = new Distrito { IdProvincia = idProvincia };
            return View(distrito);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Distrito model)
        {
            await _context.Distrito.AddAsync(model); //insert
            await _context.SaveChangesAsync();//commit
            return RedirectToAction("Index", new { id = model.IdProvincia });
        }

        //GET
        public async Task<IActionResult> Edit(int id) //abrir la pantalla
        {
            var distrito = await _context.Distrito.FindAsync(id); // select * from Distrito where PK = id
            return View(distrito); //retornar vista
        }

        [HttpPost] //-> hacer el cambio 
        public async Task<IActionResult> Edit(Distrito model)
        {
            var modelOld = await _context.Distrito.FindAsync(model.Id);
            modelOld.NombreDistrito = model.NombreDistrito;
            _context.Update(modelOld); // update en provincia  
            await _context.SaveChangesAsync(); //comit a la base de datos
            return RedirectToAction("Index", new { id = model.IdProvincia });
        }

        public async Task<IActionResult> Delete(int id)
        {
            var idProvincia = 0;
            var distrito = await _context.Distrito.FindAsync(id);
            if (distrito != null)
            {
                idProvincia = distrito.IdProvincia;
                _context.Remove(distrito);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index", new { id = idProvincia });
        }
    }
}

TrabajadoresPrueba/Controllers/ProvinciasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TrabajadoresPrueba.Data;
using TrabajadoresPrueba.Modelos;

namespace TrabajadoresPrueba.Controllers
{
    public class ProvinciasController : Controller
    {
        private readonly DataContext _context;

        public ProvinciasController(DataContext dataContext)
        {
            _context = dataContext;
        }

        //GET
        public async Task<IActionResult> Index(int id) //
        {
            var provincias = await _context.Provincia.Where(t => t.IdDepartamento.Equals(id)).ToListAsync(); //dentro de la vista departamentos
            var modelDepartamento = await _context.Departamento.FindAsync(id);
            ViewBag.Departamento = modelDepartamento;
            return View(provincias); //vista de provincias
        }

        //GET 
        public IActionResult Create(int idDepartamento) //trae el ID del departamento 
        {
            var provincia = new Provincia { IdDepartamento = idDepartamento }; 
            return View(provincia);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Provincia model)
        {
            await _context.Provincia.AddAsync(model); //
            await _context.SaveChangesAsync(); //comit a la base de datos
            return RedirectToAction("Index", new { id = model.IdDepartamento });
        }

        //GET -> obtener el registro
        public async Task<IActionResult> Edit(int id) //abrir la pantalla
        {
            var provincia = await _context.Provincia.FindAsync(id); // select * from Provincia where PK = id
            return View(provincia); //retornar vista
        }

        [HttpPost] //-> hacer el cambio 
        public async Task<IActionResult> Edit(Provincia model)
        {
            var modelOld = await _context.Provincia.FindAsync(model.Id);
            modelOld.NombreProvincia = model.NombreProvincia;
            _context.Update(modelOld); // update en provincia 
            await _context.SaveChangesAsync(); //comit a la base de datos
            return RedirectToAction("Index", new { id = model.IdDepartamento });
        }

        public async Task<IActionResult> Delete(int id)
        {
            var idDepartamento = 0;
            var provincia = await _context.Provincia.FindAsync(id);
            if (provincia != null)
            {
                idDepartamento = provincia.IdDepartamento;
                _context.Remove(provincia);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index", new { id = idDepartamento });

        }
    }
}

TrabajadoresPrueba/Views/Provincias/Create.cshtml
@model TrabajadoresPrueba.Modelos.Provincia
<div class="ibox-content">
    <div class="row">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="IdDepartamento" class="form-control"/>
            <div class="col col-sm-12">
                <div class="form-group">
                    <div class="input text">
                        <label asp-for="NombreProvincia" class="control-label"></label>
                        <input asp-for="NombreProvincia" class="form-control" required />
                        <span asp-validation-for="NombreProvincia" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="col col-sm-12 text-right">
                <div class="form-group">
                    <input type="submit" value="Guardar" class="btn btn-success" />
                </div>
            </div>
        </form>
    </div>
</div>

TrabajadoresPrueba/Views/Provincias/Edit.cshtml
@model TrabajadoresPrueba.Modelos.Provincia
<div class="ibox-content">
    <div class="row">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="IdDepartamento" class="form-control" hidden />
            <div class="col col-sm-12">
                <div class="form-group">
                    <div class="input text">
                        <label asp-for="NombreProvincia" class="control-label"></label>
                        <input asp-for="NombreProvincia" class="form-control" required />
                        <span asp-validation-for="NombreProvincia" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="col col-sm-12 text-right">
                <div class="form-group">
                    <input type="submit" value="Guardar" class="btn btn-success" />
                </div>
            </div>
        </form>
    </div>
</div>

TrabajadoresPrueba/Views/Provincias/Index.cshtml
@model IEnumerable<TrabajadoresPrueba.Modelos.Provincia>
[17:49] Bruno Sánchez Escajadillo

@{
    var parametroDepartamento = (TrabajadoresPrueba.Modelos.Departamento)ViewBag.Departamento;
}
<div class="mail-box">
    <h3>Departamento: @parametroDepartamento.NombreDepartamento</h3>
    <h2>Provincias</h2>
    <p>
        <a asp-action="Create" asp-route-idDepartamento="@parametroDepartamento.Id" class="btn btn-primary info-dialog-window">Nuevo Registro</a>
    </p>
    <div class="table-responsive table-sm table-hover">
        <table id="example" class="table table-hover table-mail">
            <thead class="table-active">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.NombreProvincia)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.NombreProvincia)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning infoObser-dialog-window">Editar</a>
                            <a data-id="@item.Id" class="btn btn-danger delete-dialog-window">Eliminar</a>
                            <a asp-controller="Distritos" asp-action="Index" asp-route-id="@item.Id" class="btn btn-info">Distritos</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <a asp-controller="Departamentos" class="btn btn-dark" asp-action="Index" >Regresar a la lista</a>
    </div>
</div>

<div class="modal fade" id="Anular" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="background-color:#da2213;color:white;">
                <button data-dismiss="modal" class="close" type="button">
                    <span aria-hidden="true">×</span>
                    <span class="sr-only">Close</span>
                </button>
                <h2 class="modal-title">Eliminar Provincia</h2>
            </div>
            <div class="modal-body">
                <div class="text-center">
                    <h4>¿Estas seguro de eliminar el registro seleccionado?</h4>
                </div>
                <div id="response" class="text-right">
                </div>
            </div>
        </div>
    </div>
</div>




@section Scripts {



    <script>
        $("body").on("click", "a.delete-dialog-window", null, function (e) {
            var htmlContent = '<br /><button type="button" id="btnNo" class="btn btn-danger" style="background-color:#da2213;color:white;" data-dismiss="modal" aria-hidden="true">No</button>&nbsp&nbsp<a href="@Url.Action("Delete", "Provincias")/' + $(this).data('id') + '" class="btn btn-default">Si</a>';
            $("#response").html(htmlContent);
            $('#Anular').modal('show');
        });
    </script>
}